### ISSUE TITLE
Lösung für pull-request-erstellen.md von HenryDevGit

### ISSUE THREAD

**Issue by HenryDevGit** [wulfland/CodingDojo#102]
[ ] Fork erstellen  
[ ] Fork klonen  
[ ] Upstream konfigurieren  
[ ] Branch erstellen und Änderungen durchführen  
[ ] Issue anlegen  
[ ] Pull-Request erstellen  
[ ] Änderungen aus Upstream laden und mergen

**Comment by wulfland** [comment]
Hallo @HenryDevGit - ich hab gerade erst gesehen, dass mein Workflow nicht mehr lief. Die Kata hat vermutlich bei dir nicht funktioniert. Kannst du es nochmals probieren? Bei mir hat es jetzt funktioniert.
